---
- name: Include default vars of role.
  include_vars: "default.yml"

- name: Enable iptables bridge.
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: Download minikube.
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: 0755

- name: Add kubernetes repository.
  yum_repository:
    name: Kubernetess
    description: Docker CE Stable - $basearch
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey:
      - "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"

- name: Install kubectl.
  yum:
    name: "kubectl"
    state: "present"

- name: Configure settings for minikube.
  template:
    src: "minikube.sh.j2"
    dest: "/etc/profile.d/minikube.sh"
    mode: "u=rw,g=r,o=r"
  notify: Start minikube none driver
