---
- name: reset ssl certificate
  lineinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    state: present
    backrefs: yes
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^#?\s*SSLCertificateFile'
      line: 'SSLCertificateFile /etc/letsencrypt/live/{{ domain_name }}/cert.pem'
    - regexp: '^#?\s*SSLCertificateChainFile'
      line: 'SSLCertificateChainFile /etc/letsencrypt/live/{{ domain_name }}/chain.pem'
    - regexp: '^#?\s*SSLCertificateKeyFile'
      line: 'SSLCertificateKeyFile /etc/letsencrypt/live/{{ domain_name }}/privkey.pem'

- name: restart apache server
  service:
    name: "{{ apache_service }}"
    state: restarted

