---
- name: Include default vars of role.
  include_vars: "default.yml"

- name: Set current timezone to Asia/Tokyo
  timezone:
    name: "Asia/Tokyo"

- name: Dissable the services automatic start on boot.
  service:
    name: "{{ item }}"
    enabled: no
  with_items: "{{ disable_auto_startup_services }}"

- name: Install scl repositories
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "centos-release-scl"
    - "centos-release-scl-rh"

- name: Install the rh-ruby25 from the centos-sclo-rh repo
  yum:
    name: rh-ruby25
    enablerepo: centos-sclo-rh
    state: present
  notify:
    - enable ruby bash

- name: Flush handlers immediately
  meta:
    flush_handlers

- name: Installs latest available version of jekyll.
  gem:
    name: jekyll
    state: latest
  environment:
    # LD_LIBRARY_PATH: '/opt/rh/rh-ruby25/root/usr/lib64:{{ ansible_env.LD_LIBRARY_PATH }}'
    PATH: '/opt/rh/rh-ruby25/root/usr/bin:{{ ansible_env.PATH }}'

# - name: test
#   shell: gem install jekyll bundler
# source /opt/rh/rh-ruby25/enable
